[changelog]
header = "# Changelog\n\nAll RPM packaging changes for node_exporter are documented here.\n"
body = """
{% if version %}\
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_preprocessors = []
commit_parsers = [
  { message = "^feat",        group = "Features" },
  { message = "^fix",         group = "Bug Fixes" },
  { message = "^chore: bump", group = "Upstream Updates" },
  { message = "^chore",       group = "Miscellaneous" },
  { message = "^docs",        group = "Documentation" },
  { message = "^ci",          group = "CI/CD" },
  { message = "^refactor",    group = "Refactoring" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
